
import React, { useState, useEffect } from 'react';

import { View, Student, Teacher, Subject } from './types';
import Login from './pages/Login';
import Register from './pages/Register';
import Dashboard from './pages/Dashboard';
import Students from './pages/Students';
import Teachers from './pages/Teachers';
import Subjects from './pages/Subjects';
import BottomNav from './components/BottomNav';
import Sidebar from './components/Sidebar';
import TopAppBar from './components/TopAppBar';
import { supabase } from './lib/supabase';
import { authService } from './services/auth';
import { studentsService } from './services/students';
import { teachersService } from './services/teachers';
import { subjectsService } from './services/subjects';

const App: React.FC = () => {
  const [currentView, setCurrentView] = useState<View>(View.LOGIN);
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(false);
  const [darkMode, setDarkMode] = useState<boolean>(false);

  // Global State
  const [students, setStudents] = useState<Student[]>([]);
  const [teachers, setTeachers] = useState<Teacher[]>([]);
  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Auth Listener
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (session) {
        setIsAuthenticated(true);
        if (currentView === View.LOGIN || currentView === View.REGISTER) {
          setCurrentView(View.DASHBOARD);
        }
        fetchStudents();
        fetchTeachers();
        fetchSubjects();
      } else {
        setIsAuthenticated(false);
        setCurrentView(View.LOGIN);
        setStudents([]);
        setTeachers([]);
        setSubjects([]);
      }
      setIsLoading(false);
    });

    return () => subscription.unsubscribe();
  }, []);

  const fetchStudents = async () => {
    const { data, error } = await studentsService.getStudents();
    if (data) setStudents(data);
  };

  const fetchTeachers = async () => {
    const { data, error } = await teachersService.getTeachers();
    if (data) setTeachers(data);
  };

  const fetchSubjects = async () => {
    const { data, error } = await subjectsService.getSubjects();
    if (data) setSubjects(data);
  };

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  // Handle Login is now just a state update triggered by the auth listener, 
  // but to keep the prop interface for Login page (if it expects a callback),
  // we can keep it empty or remove it if Login page handles logic.
  // For now, let's keep it as is, but logic moves to Login page component calling service.
  const handleLogin = () => {
    // Legacy: controlled by auth listener now
  };

  const handleLogout = async () => {
    await authService.signOut();
    // Auth listener will handle state update
  };

  // Student CRUD
  const saveStudent = async (student: Student) => {
    // Optimistic update or refresh? Let's refresh for simplicity first, or update local state.
    // If ID exists in our list, it's an update. But 'student' passed might not have ID if new?
    // Wait, Student interface has ID. Creating new needs to handle ID generation (done by DB).
    // The UI 'Students' component likely passes a student object.

    // Check if it's a confusing logic in UI: does onSave pass a full student with ID?
    // Assuming if ID is set/known it's update, otherwise... existing code generated ID? 
    // Existing code: setStudents(prev => exists ? update : [student, ...prev]). ID was probably generated by UI.
    // We should let DB generate ID.

    try {
      if (students.some(s => s.id === student.id)) {
        // Update
        const { data, error } = await studentsService.updateStudent(student.id, student);
        if (error) throw error;
        if (data) {
          setStudents(prev => prev.map(s => s.id === data.id ? data : s));
        }
      } else {
        // Create - we need to omit ID if it's empty/temp, or handle it.
        // Assuming UI generates a temp ID we should ignore, or UI handles "new" vs "edit".
        // Let's assume for now we try to create.

        // IMPORTANT: The 'student' object from UI likely has a temp ID or is complete. 
        // We should strip ID for creation if it's not a real UUID from DB.
        // For safety, let's try to update if ID exists in our list (real), else create.

        // Actually, better: if the ID exists in the specific list `students` which comes from DB, then it is an update.
        // If not, it is a create.

        const { id, ...rest } = student;
        // If it's a new student, the UI might have generated a fake ID.
        // We call createStudent with Rest.

        // BUT, wait, if I stripped ID, how do I know if I should update?
        // Let's check if the ID looks like a UUID or if it is in the current list.
        const isUpdate = students.some(s => s.id === student.id);

        if (isUpdate) {
          const { data, error } = await studentsService.updateStudent(student.id, rest); // Pass rest or student? updateStudent takes Partial.
          if (error) throw error;
          if (data) setStudents(prev => prev.map(s => s.id === data.id ? data : s));
        } else {
          const { data, error } = await studentsService.createStudent(rest);
          if (error) throw error;
          if (data) setStudents(prev => [data, ...prev]);
        }
      }
    } catch (err) {
      console.error(err);
      console.error(err);
      alert(`Erro ao salvar aluno: ${err.message || JSON.stringify(err)}`);
    }
  };

  const deleteStudent = async (id: string) => {
    const { error } = await studentsService.deleteStudent(id);
    if (error) {
      alert('Erro ao excluir aluno.');
      return;
    }
    setStudents(prev => prev.filter(s => s.id !== id));
  };

  // Teacher CRUD
  const saveTeacher = async (teacher: Teacher) => {
    try {
      if (teachers.some(t => t.id === teacher.id)) {
        const { data, error } = await teachersService.updateTeacher(teacher.id, teacher);
        if (error) throw error;
        if (data) setTeachers(prev => prev.map(t => t.id === data.id ? data : t));
      } else {
        const { id, ...rest } = teacher;
        const isUpdate = teachers.some(t => t.id === teacher.id);
        if (isUpdate) {
          // Fallback logic similar to students if needed, but redundant with above if check
          const { data, error } = await teachersService.updateTeacher(teacher.id, rest);
          if (data) setTeachers(prev => prev.map(t => t.id === data.id ? data : t));
        } else {
          const { data, error } = await teachersService.createTeacher(rest);
          if (error) throw error;
          if (data) setTeachers(prev => [data, ...prev]);
        }
      }
    } catch (err) {
      console.error(err);
      alert('Erro ao salvar professor.');
    }
  };

  const deleteTeacher = async (id: string) => {
    const { error } = await teachersService.deleteTeacher(id);
    if (error) {
      alert('Erro ao excluir professor.');
      return;
    }
    setTeachers(prev => prev.filter(t => t.id !== id));
  };

  // Subject CRUD
  const saveSubject = async (subject: Subject) => {
    try {
      if (subjects.some(s => s.id === subject.id)) {
        const { data, error } = await subjectsService.updateSubject(subject.id, subject);
        if (error) throw error;
        if (data) setSubjects(prev => prev.map(s => s.id === data.id ? data : s));
      } else {
        const { id, ...rest } = subject;
        const { data, error } = await subjectsService.createSubject(rest);
        if (error) throw error;
        if (data) setSubjects(prev => [data, ...prev]);
      }
    } catch (err) {
      console.error(err);
      alert('Erro ao salvar matéria.');
    }
  };

  const deleteSubject = async (id: string) => {
    const { error } = await subjectsService.deleteSubject(id);
    if (error) {
      alert('Erro ao excluir matéria.');
      return;
    }
    setSubjects(prev => prev.filter(s => s.id !== id));
  };

  const renderContent = () => {
    if (!isAuthenticated) {
      if (currentView === View.REGISTER) {
        return <Register onBack={() => setCurrentView(View.LOGIN)} onComplete={handleLogin} />;
      }
      return <Login onLogin={handleLogin} onRegisterClick={() => setCurrentView(View.REGISTER)} />;
    }

    switch (currentView) {
      case View.DASHBOARD:
        return <Dashboard studentsCount={students.length} teachersCount={teachers.length} subjectsCount={subjects.length} />;
      case View.STUDENTS:
        return <Students students={students} onSave={saveStudent} onDelete={deleteStudent} />;
      case View.TEACHERS:
        return <Teachers teachers={teachers} subjects={subjects} onSave={saveTeacher} onDelete={deleteTeacher} />;
      case View.SUBJECTS:
        return <Subjects subjects={subjects} onSave={saveSubject} onDelete={deleteSubject} />;
      case View.SETTINGS:
        return (
          <div className="p-4 md:p-8 max-w-4xl animate-in fade-in duration-500">
            <h1 className="text-2xl md:text-3xl font-bold mb-8 tracking-tight">Configurações</h1>
            <div className="space-y-6">
              <div className="bg-white dark:bg-gray-800 rounded-3xl p-6 md:p-8 shadow-sm border border-gray-100 dark:border-gray-700">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="size-10 md:size-12 rounded-2xl bg-slate-100 dark:bg-gray-700 flex items-center justify-center">
                      <span className="material-symbols-outlined text-primary">dark_mode</span>
                    </div>
                    <div>
                      <span className="font-bold text-base md:text-lg block leading-tight">Interface Visual</span>
                      <span className="text-[10px] md:text-sm text-slate-400 font-medium">Tema claro/escuro</span>
                    </div>
                  </div>
                  <button
                    onClick={() => setDarkMode(!darkMode)}
                    className={`w-12 h-6 md:w-14 md:h-7 rounded-full transition-all relative ${darkMode ? 'bg-primary' : 'bg-slate-200'}`}
                  >
                    <div className={`absolute top-1 w-4 h-4 md:w-5 md:h-5 bg-white rounded-full shadow-sm transition-all ${darkMode ? 'left-7 md:left-8' : 'left-1'}`} />
                  </button>
                </div>
              </div>

              <div className="bg-white dark:bg-gray-800 rounded-3xl p-6 md:p-8 shadow-sm border border-gray-100 dark:border-gray-700">
                <h3 className="font-bold text-base md:text-lg mb-4 text-red-500">Ações</h3>
                <button
                  onClick={handleLogout}
                  className="w-full md:w-auto px-8 py-3 bg-red-50 dark:bg-red-900/10 text-red-600 rounded-2xl font-black uppercase tracking-widest text-[10px] hover:bg-red-100 transition-all flex items-center justify-center gap-2"
                >
                  <span className="material-symbols-outlined text-lg">logout</span>
                  Encerrar Sessão
                </button>
              </div>
            </div>
          </div>
        );
      default:
        return <Dashboard studentsCount={students.length} teachersCount={teachers.length} subjectsCount={subjects.length} />;
    }
  };

  return (
    <div className="h-screen bg-background-light dark:bg-background-dark flex flex-col md:flex-row overflow-hidden transition-colors duration-300">
      {isAuthenticated && <Sidebar activeView={currentView} onViewChange={setCurrentView} onLogout={handleLogout} />}

      <div className="flex-1 flex flex-col h-full overflow-hidden">
        {isAuthenticated && (
          <TopAppBar
            title={
              currentView === View.DASHBOARD ? "Painel" :
                currentView === View.STUDENTS ? "Alunos" :
                  currentView === View.TEACHERS ? "Professores" :
                    currentView === View.SUBJECTS ? "Matérias" :
                      "Ajustes"
            }
          />
        )}

        <main className={`flex-1 overflow-y-auto no-scrollbar relative ${isAuthenticated ? 'pb-24 md:pb-8' : ''}`}>
          <div className={`${isAuthenticated ? 'container mx-auto px-4 md:px-0 max-w-[1600px]' : 'max-w-lg mx-auto min-h-full'}`}>
            {renderContent()}
          </div>
        </main>

        {isAuthenticated && (
          <div className="md:hidden">
            <BottomNav activeView={currentView} onViewChange={setCurrentView} />
          </div>
        )}
      </div>
    </div>
  );
};

export default App;
